"""
Script Name: validate_schema_report.py
Author: Brooke Reams (breams@esri.com)
Date: May 11, 2026

Description:
    Finds and reports errors in the vaidation Excel spreadsheet created by
    the Generate Schema Report GP tool.

Inputs:
    - in_xls (str): Path to an Excel file generated by the Generate Schema
        Report GP tool.

Outputs:
    - out_xls (str): Path (including file name) to the output report xls file
        containing error details.

Notes:
    - This script is written to read Excel files generated by the Generate Schema
        Report GP tool.  Rows can be added/removed from the categories in the Excel
        spreadsheet, however category names ('Field', 'Subtype', 'SubtypeFieldInfo',
        etc) and column names should not be altered.

Versions:
    - ArcGIS Pro 3.6
    - Python 3.11.11

Copyright (c) 2026 Esri. All rights reserved.

Updates:

"""

import arcpy
import warnings
import re
import os
import openpyxl
from openpyxl.utils import get_column_letter
from openpyxl.styles import Alignment


def log_it(message, level=0):
    print(message)
    if level == 0:
        arcpy.AddMessage(message)
    elif level == 1:
        arcpy.AddWarning(message)
    else:
        arcpy.AddError(message)


def autofit_column_widths(ws):
    for col in ws.columns:
        max_length = 0
        column = get_column_letter(
            col[0].column
        )  # Get column letter from the first cell in the column
        for cell in col:
            try:
                if len(str(cell.value)) > max_length:
                    max_length = len(str(cell.value))
            except (
                TypeError
            ):  # Handle cases where cell.value might be None or not easily convertible to string
                pass
        adjusted_width = max_length + 2  # Add some padding
        ws.column_dimensions[column].width = adjusted_width


def is_default_val_out_of_range(default_val, minimum, maximum):
    return (
        default_val < domain_dict[domain_name]["minimum"]
        or default_val > domain_dict[domain_name]["maximum"]
    )


def search_start_row(ws, col_start_index, col_end_index, search_text1, search_text2):
    for col in ws.iter_cols(min_col=col_start_index, max_col=col_end_index):
        for cell in col:
            if (
                cell.value == search_text1
                and col[col.index(cell) + 1].value == search_text2
            ):
                return cell.row + 2
    return None


def search_end_row(ws, row, col_index):
    for row in ws.iter_rows(min_row=row, min_col=col_index, max_col=col_index):
        for cell in row:
            if cell.value is None:
                return cell.row - 1
    return None


# Input xls file
in_xls = arcpy.GetParameterAsText(0)
out_xls = arcpy.GetParameterAsText(1)

# Open workbook (but ignore warning)
with warnings.catch_warnings(record=True):
    warnings.filterwarnings("ignore", category=UserWarning, module="openpyxl")
    wb = openpyxl.load_workbook(in_xls)

# Get fc and table sheet names
log_it("Finding all feature class and table worksheets in input Excel file")
ds_sheets = [
    wb[sheet_name]
    for sheet_name in wb.sheetnames
    if re.search("^FC[0-9]+_", sheet_name) or re.search("^T[0-9]+_", sheet_name)
]

# Get domain sheet names
log_it("Getting list of domains")
domain_sheets = [
    wb[sheet_name] for sheet_name in wb.sheetnames if re.search("^D[0-9]+_", sheet_name)
]

# Init dictionary to store domain name and domain properties
domain_dict = (
    {}
)  # {domain name: {field type: string, domain type: Coded Value, codes: [code, code], range: (1, 50), max length: 4}}
# Loop through domain sheets to get domain details
log_it("Getting domain properties")
for ws in domain_sheets:
    domain_name = ws["B9"].value
    d = {
        "field type": None,
        "domain type": None,
        "codes": [],
        "max length": 0,
        "minimum": None,
        "maximum": None,
    }
    field_type = ws["B11"].value
    domain_type = ws["B12"].value
    if domain_type == "Coded Value":
        codes = []
        max_length = 0
        start_row = search_start_row(ws, 1, 1, "DomainCodedValue", "Code")
        end_row = search_end_row(ws, start_row, 1)
        if start_row and end_row:
            for i in range(start_row, end_row + 1):
                code = ws[f"A{i}"].value
                codes.append(code)
                if field_type == "String":
                    if len(code) > max_length:
                        max_length = len(code)
            d["codes"] = codes
            d["max length"] = max_length
    else:
        start_row = start_row = search_start_row(ws, 1, 1, "DomainRange", "Minimum")
        d["minimum"] = ws[f"A{start_row}"].value
        d["maximum"] = ws[f"B{start_row}"].value

    d["field type"] = field_type
    d["domain type"] = domain_type
    domain_dict[domain_name] = d

# Init dictionary to store dataset errors
log_it("Searching for errors")
ds_errors_dict = {}  # {ws name: {subtype errors: [], domain errors: []}}
# Loop through dataset worksheets
for ws in ds_sheets:
    # Init errors found bool
    errors_found = False
    # Init current errors dictionary
    cur_dict = {
        "Field Category Errors": [],
        "Subtype Category Errors": [],
        "SubtypeFieldInfo Category Errors": [],
    }
    # Get subtype info
    start_row = search_start_row(ws, 1, 1, "Subtype", "Name")
    end_row = search_end_row(ws, start_row, 1)

    # Get subtype field info
    start_row = search_start_row(ws, 1, 1, "SubtypeFieldInfo", "Name")
    end_row = search_end_row(ws, start_row, 1)

    # Find row where fields begin
    start_row = search_start_row(ws, 1, 1, "Field", "Name")
    end_row = search_end_row(ws, start_row, 1)
    if start_row and end_row:
        # Loop through fields, get dictionary of field names with data type and length properites, check for subtypes
        flds_dict = {}  # {fld name: {data type: string, length: 12}}
        subtype_fld = None
        for i in range(start_row, end_row + 1):
            field = ws[f"A{i}"].value
            flds_dict[ws[f"A{i}"].value.lower()] = {
                "data type": ws[f"C{i}"],
                "length": ws[f"J{i}"],
            }
            # Check if field is subtype
            if str(ws[f"D{i}"].value).lower() == "subtype":
                subtype_fld = str(ws[f"A{i}"].value).lower()
                # Check if integer
                if not "integer" in str(ws[f"C{i}"].value).lower():
                    errors_found = True
                    cur_dict["Field Category Errors"].append(
                        (f"Subtype field '{subtype_fld}' data type is not int", i)
                    )

            # Check if field is domain
            if ws[f"F{i}"].value:
                domain_name = ws[f"F{i}"].value
                # Check domain dict for domain name
                if domain_name not in domain_dict.keys():
                    errors_found = True
                    cur_dict["Field Category Errors"].append(
                        (
                            f"Field '{field}': Domain '{domain_name}' in Fields was not found in spreadsheet",
                            i,
                        )
                    )
                else:
                    # Get default value and field name listed for domain
                    default_val = ws[f"G{i}"].value
                    field_name = ws[f"A{i}"].value

                    if default_val:
                        # Domain name found, check default value exists in codes
                        if domain_dict[domain_name]["domain type"] == "Coded Value":
                            if default_val not in domain_dict[domain_name]["codes"]:
                                errors_found = True
                                cur_dict["Field Category Errors"].append(
                                    (
                                        f"Field '{field}': Domain '{domain_name}' default value of '{default_val}' in Fields was not found in the domain codes",
                                        i,
                                    )
                                )

                            # Check if field length is large enough for longest code
                            max_code_length = domain_dict[domain_name]["max length"]
                            if field_name in list(flds_dict.keys()):
                                fld_type = flds_dict[field_name]["data type"]
                                if fld_type == "String":
                                    fld_length = flds_dict[field_name]["length"]
                                    if fld_length <= max_code_length:
                                        errors_found = True
                                        cur_dict["Field Category Errors"].append(
                                            (
                                                f"Field '{field}': Domain '{domain_name}' in Fields has coded value that exceeds field {field_name} length of {fld_length}",
                                                i,
                                            )
                                        )

                        # Domain name found, check default value is within range
                        else:
                            if is_default_val_out_of_range(
                                default_val,
                                domain_dict[domain_name]["minimum"],
                                domain_dict[domain_name]["maximum"],
                            ):
                                errors_found = True
                                cur_dict["Field Category Errors"].append(
                                    (
                                        f"Field '{field}': Domain '{domain_name}' default value of {default_val} in Fields was not found within the domain range",
                                        i,
                                    )
                                )

    # If subtype found, validate subtype requirements
    if subtype_fld:
        # Check for presence of at least one row under Subtype category
        start_row = search_start_row(ws, 1, 1, "Subtype", "Name")
        # if ws[f"A{start_row}"].value is None:
        if not ws[f"A{start_row}"].value:
            cur_dict["Subtype Category Errors"].append("No subtype values listed")
            continue
        # Get all subtype values listed
        end_row = search_end_row(ws, start_row, 1)
        subtype_list = []
        for i in range(start_row, end_row + 1):
            subtype_list.append(str(ws[f"A{i}"].value).lower())

        # Search subtype field info category
        start_row = search_start_row(ws, 1, 1, "SubtypeFieldInfo", "Subtype Name")
        end_row = search_end_row(ws, start_row, 1)
        # Init set for subtype field info names
        subtype_fld_info_subtype_list = set()
        # Init set for subtype field info field names
        subtype_fld_info_fld_list = set()
        # Loop through all subtype field info rows
        subtype_fld_info_domain_list = (
            []
        )  # [{domain name: {default value: abc, field name: assettype}}]
        for i in range(start_row, end_row + 1):
            subtype_fld_info_subtype_list.add(ws[f"A{i}"].value.lower())
            subtype_fld_info_fld_list.add(ws[f"C{i}"].value.lower())
            if ws[f"E{i}"].value:
                subtype_fld_info_domain_list.append(
                    {
                        ws[f"E{i}"].value: {
                            "default value": ws[f"D{i}"].value,
                            "field name": ws[f"C{i}"],
                        }
                    }
                )

        # Check for subtype info field names in list of dataset fields
        for fld in subtype_fld_info_fld_list:
            if fld not in list(flds_dict.keys()):
                errors_found = True
                cur_dict["SubtypeFieldInfo Category Errors"].append(
                    (
                        f"Field '{fld}' in SubtypeFieldInfo was not found in list of fields",
                        i,
                    )
                )

        # Check for subtype info subtype names in subtype names list
        for subtype in subtype_fld_info_subtype_list:
            if subtype not in subtype_list:
                errors_found = True
                cur_dict["SubtypeFieldInfo Category Errors"].append(
                    (
                        f"Subtype '{subtype}' in SubtypeFieldInfo was not found in list of subtypes",
                        i,
                    )
                )

        # Check for domains
        if subtype_fld_info_domain_list:
            for d in subtype_fld_info_domain_list:
                for domain_name, item_details in d.items():
                    # Check domain dict for domain name
                    if domain_name not in domain_dict.keys():
                        errors_found = True
                        cur_dict["SubtypeFieldInfo Category Errors"].append(
                            (
                                f"Domain '{domain_name}' in SubtypeFieldInfo was not found in spreadsheet",
                                i,
                            )
                        )
                    else:
                        # Get default value and field name listed for domain
                        default_val = item_details["default value"]
                        field_name = item_details["field name"]

                        if default_val:
                            # Domain name found, check default value exists in codes
                            if domain_dict[domain_name]["domain type"] == "Coded Value":
                                if default_val not in domain_dict[domain_name]["codes"]:
                                    errors_found = True
                                    cur_dict["SubtypeFieldInfo Category Errors"].append(
                                        (
                                            f"Domain '{domain_name}' default value of '{default_val}' in SubtypeFieldInfo was not found in the domain codes",
                                            i,
                                        )
                                    )

                                # Check if field length is large enough for longest code
                                max_code_length = domain_dict[domain_name]["max length"]
                                if field_name in list(flds_dict.keys()):
                                    fld_type = flds_dict[field_name]["data type"]
                                    if fld_type == "String":
                                        fld_length = flds_dict[field_name]["length"]
                                        if fld_length <= max_code_length:
                                            errors_found = True
                                            cur_dict[
                                                "SubtypeFieldInfo Category Errors"
                                            ].append(
                                                (
                                                    f"Domain '{domain_name}' in SubtypeFieldInfo has coded value that exceeds field '{field_name}' length of {fld_length}",
                                                    i,
                                                )
                                            )

                            # Domain name found, check default value is within range
                            else:
                                if is_default_val_out_of_range(
                                    default_val,
                                    domain_dict[domain_name]["minimum"],
                                    domain_dict[domain_name]["maximum"],
                                ):
                                    errors_found = True
                                    cur_dict["SubtypeFieldInfo Category Errors"].append(
                                        (
                                            f"Domain '{domain_name}' default value of '{default_val}' in SubtypeFieldInfo was not found within the domain range",
                                            i,
                                        )
                                    )

    if errors_found:
        ds_errors_dict[ws.title] = cur_dict


if ds_errors_dict:
    log_it("Errors were found... creating errors report")
    # Create new workbook
    wb = openpyxl.Workbook()
    ws = wb.active
    ws["A1"] = "Sheet Name"
    ws["B1"] = "Row Number"
    ws["C1"] = "Error Category"
    ws["D1"] = "Error Description"

    # Bold first row
    bold_font = openpyxl.styles.Font(bold=True)
    for cell in ws[1]:
        cell.font = bold_font
    row = 2
    for ds, errors in ds_errors_dict.items():
        log_it(ds)
        if errors["Field Category Errors"]:
            log_it("Field Category Errors:")
            for e in errors["Field Category Errors"]:
                log_it(f"\t{e}")
                ws[f"A{row}"] = ds
                ws[f"B{row}"] = e[1]
                ws[f"C{row}"] = "Field Category Error"
                ws[f"D{row}"] = e[0]
                row += 1

        if errors["Subtype Category Errors"]:
            log_it("Subtype Category Errors:")
            for e in errors["Subtype Category Errors"]:
                log_it(f"\t{e}")
                ws[f"A{row}"] = ds
                ws[f"B{row}"] = e[1]
                ws[f"C{row}"] = "Subtype Category Error"
                ws[f"D{row}"] = e[0]
                row += 1

        if errors["SubtypeFieldInfo Category Errors"]:
            log_it("SubtypeFieldInfo Category Errors:")
            for e in errors["SubtypeFieldInfo Category Errors"]:
                log_it(f"\t{e}")
                ws[f"A{row}"] = ds
                ws[f"B{row}"] = e[1]
                ws[f"C{row}"] = "SubtypeFieldInfo Category Error"
                ws[f"D{row}"] = e[0]
                row += 1

        # Apply autofit to column
        autofit_column_widths(ws)

        # Save excel
        wb.save(out_xls)

        # Start file
        os.startfile(out_xls)

else:
    log_it("No errors were found in input file!")
